### ISSUE TITLE
Menu items are labeled "Script200", "Script202", etc

### ISSUE THREAD

**Issue by Valvarexart** [lzoubek/xbmc-plugin-mpdc#18]
Is this intentional? Are they just placeholder items?

Picture: http://i.imgur.com/HkqsYwa.jpg

**Comment by bserem** [comment]
Openelec5 has the same problem. Also many of the menu items are kind of misaligned (they are right aligned and part of them hidden).

I don't really get any clues from the code on how to fix this :)

**Comment by remschneid** [comment]
Hi all,
same problems for me with kodi 14.1 on Raspbian. I was able to fix the problems on the 2.0.7 version from the official kodi repo. So just download the ZIP File from <b>remschneid/xbmc.script.mpdc</b> and merge the files contained in the ZIP with an already installed 2.0.7 version.

**Comment by bserem** [comment]
@remschneid could you please fork this repo and apply your fixes there? So that:
a) commit history from the original project is kept
b) you can create a pull-request towards here (hoping that the maintainer will see it and merge it)

Thanks for your work ;)

**Comment by remschneid** [comment]
Am 15.03.2015 um 01:32 schrieb Bill Seremetis:
>
> @remschneid <https://github.com/remschneid> could you please fork this
> repo and apply your fixes there? So that:
> a) commit history from the original project is kept
> b) you can create a pull-request towards here (hoping that the
> maintainer will see it and merge it)
>
> Thanks for your work ;)
>
Hi Bill,
I've forked the repo, created a new branch named "frodo_issue" and
applied the patches there. Pull-request is also done, hope
I've done all right,

greets Rüdiger

**Comment by bserem** [comment]
Seems ok! Thanks :)

Let's hope that the original maintainer will see it and merge it. In the meanwhile I'll be using your updated files

**Comment by remschneid** [comment]
Hi Bill,
just received an e-mail from Libor, the 2.0.8 goes to the official repo.

Best regards Rüdiger

**Comment by lzoubek** [comment]
2.0.8 was added to helix repo, closing this
